Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,20 +35,24 @@ jobs:
       - run:
           name: Start LocalStack
           command: |
-            pip3 install awscli-local[ver1]    
+            pip3 install awscli-local[ver1]
+            localstack start -d
+            echo "Waiting for LocalStack startup..."  
+            localstack wait -t 30                     
+            echo "Startup complete"  
       - run:
           name: check node version
           command: awslocal s3 mb s3://test-bucket
-      - run:
-          name: Waiting for localstack to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z localhost 4566 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for localstack && exit 1
+      # - run:
+      #     name: Waiting for localstack to be ready
+      #     command: |
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z localhost 4566 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 1
+      #       done
+      #       echo Failed waiting for localstack && exit 1
       - run:
           name: Local stack final
           command: curl localhost:4566/test-bucket
