Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,22 +8,24 @@ version: 2.1
 jobs:
   say-hello:
     docker:
-      - image: cimg/python:3.12.1-node
+      - image: cimg/node:20.11.0 
       - image: mongo
       - image: localstack/localstack
     
     steps:
       - checkout
-      - run:
-          name: Waiting for localstack to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z localhost 4566 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for localstack && exit 1
+      - setup_remote_docker:
+          docker_layer_caching: false
+      # - run:
+      #     name: Waiting for localstack to be ready
+      #     command: |
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z localhost 4566 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 1
+      #       done
+      #       echo Failed waiting for localstack && exit 1
       
           # command: |
           #   set +e
@@ -42,7 +44,9 @@ jobs:
       #       sudo apt-get install pip
       - run:
           name: Start LocalStack
-          command: pip3 install awscli-local[ver1]
+          command: |
+            docker pull python
+            pip3 install awscli-local[ver1]
             
       - run:
           name: check node version
